<?php

declare(strict_types=1);

namespace Simtabi\Laranail\Chrono\Core\Enums;

use Simtabi\Laranail\Chrono\Core\Enums\Concerns\DescribesAbbreviation;

/**
 * GENERATED by tools/generate-enums.php — do not edit by hand.
 *
 * Every timezone abbreviation PHP knows. Note most are ambiguous — 96 of these map to more than one zone, and `CST` alone matches 62 — so an abbreviation is a display label, never an identifier.
 *
 * 144 cases, generated against tzdata 2026.1. Regenerate with `laranail::chrono.sync`.
 * A parity test asserts every case is a live identifier, every identifier has a case, and that
 * regenerating reproduces this file byte for byte.
 */
enum TimezoneAbbreviation: string
{
    use DescribesAbbreviation;

    case A = 'A';
    case ACDT = 'ACDT';
    case ACST = 'ACST';
    case ADDT = 'ADDT';
    case ADT = 'ADT';
    case AEDT = 'AEDT';
    case AEST = 'AEST';
    case AHDT = 'AHDT';
    case AHST = 'AHST';
    case AKDT = 'AKDT';
    case AKST = 'AKST';
    case AMT = 'AMT';
    case APT = 'APT';
    case AST = 'AST';
    case AWDT = 'AWDT';
    case AWST = 'AWST';
    case AWT = 'AWT';
    case B = 'B';
    case BDST = 'BDST';
    case BDT = 'BDT';
    case BMT = 'BMT';
    case BST = 'BST';
    case C = 'C';
    case CAST = 'CAST';
    case CAT = 'CAT';
    case CDDT = 'CDDT';
    case CDT = 'CDT';
    case CEMT = 'CEMT';
    case CEST = 'CEST';
    case CET = 'CET';
    case CHST = 'CHST';
    case CMT = 'CMT';
    case CPT = 'CPT';
    case CST = 'CST';
    case CWT = 'CWT';
    case D = 'D';
    case DMT = 'DMT';
    case E = 'E';
    case EAT = 'EAT';
    case EDDT = 'EDDT';
    case EDT = 'EDT';
    case EEST = 'EEST';
    case EET = 'EET';
    case EMT = 'EMT';
    case EPT = 'EPT';
    case EST = 'EST';
    case EWT = 'EWT';
    case F = 'F';
    case FFMT = 'FFMT';
    case FMT = 'FMT';
    case G = 'G';
    case GDT = 'GDT';
    case GMT = 'GMT';
    case GST = 'GST';
    case H = 'H';
    case HDT = 'HDT';
    case HKST = 'HKST';
    case HKT = 'HKT';
    case HMT = 'HMT';
    case HPT = 'HPT';
    case HST = 'HST';
    case HWT = 'HWT';
    case I = 'I';
    case IDDT = 'IDDT';
    case IDT = 'IDT';
    case IMT = 'IMT';
    case IST = 'IST';
    case JDT = 'JDT';
    case JMT = 'JMT';
    case JST = 'JST';
    case K = 'K';
    case KDT = 'KDT';
    case KMT = 'KMT';
    case KST = 'KST';
    case L = 'L';
    case LST = 'LST';
    case M = 'M';
    case MDDT = 'MDDT';
    case MDST = 'MDST';
    case MDT = 'MDT';
    case MEST = 'MEST';
    case MET = 'MET';
    case MMT = 'MMT';
    case MPT = 'MPT';
    case MSD = 'MSD';
    case MSK = 'MSK';
    case MST = 'MST';
    case MWT = 'MWT';
    case N = 'N';
    case NDDT = 'NDDT';
    case NDT = 'NDT';
    case NPT = 'NPT';
    case NST = 'NST';
    case NWT = 'NWT';
    case NZDT = 'NZDT';
    case NZMT = 'NZMT';
    case NZST = 'NZST';
    case O = 'O';
    case P = 'P';
    case PDDT = 'PDDT';
    case PDT = 'PDT';
    case PKST = 'PKST';
    case PKT = 'PKT';
    case PLMT = 'PLMT';
    case PMT = 'PMT';
    case PPMT = 'PPMT';
    case PPT = 'PPT';
    case PST = 'PST';
    case PWT = 'PWT';
    case Q = 'Q';
    case QMT = 'QMT';
    case R = 'R';
    case RMT = 'RMT';
    case S = 'S';
    case SAST = 'SAST';
    case SDMT = 'SDMT';
    case SJMT = 'SJMT';
    case SMT = 'SMT';
    case SST = 'SST';
    case T = 'T';
    case TBMT = 'TBMT';
    case TMT = 'TMT';
    case U = 'U';
    case UCT = 'UCT';
    case UTC = 'UTC';
    case V = 'V';
    case W = 'W';
    case WAST = 'WAST';
    case WAT = 'WAT';
    case WEMT = 'WEMT';
    case WEST = 'WEST';
    case WET = 'WET';
    case WIB = 'WIB';
    case WIT = 'WIT';
    case WITA = 'WITA';
    case WMT = 'WMT';
    case X = 'X';
    case Y = 'Y';
    case YDDT = 'YDDT';
    case YDT = 'YDT';
    case YPT = 'YPT';
    case YST = 'YST';
    case YWT = 'YWT';
    case Z = 'Z';
}
