<?php

declare(strict_types=1);

/**
 * Generates the three backed enums that mirror the tz database:
 *
 *   Core/Enums/Timezone.php             419 canonical IANA identifiers
 *   Core/Enums/TimezoneLegacy.php       the deprecated identifiers (ALL_WITH_BC minus ALL)
 *   Core/Enums/TimezoneAbbreviation.php 144 abbreviations from listAbbreviations()
 *
 * The case-name normaliser and its collision guard are carried over from
 * `laranail/package-tools`' generator, whose enum this supersedes — case names and values are
 * identical, so migrating is a one-line `use` change.
 *
 * Generated files carry no behaviour. Each `use`s a hand-written concern instead, which keeps the
 * emitted text a pure case list and makes the byte-for-byte sync test viable: if the file is a
 * function of tzdata alone, any difference means the data moved.
 *
 * Usage:  php tools/generate-enums.php [--check]
 */
require_once __DIR__ . '/pint-format.php';

$check = in_array('--check', $argv, true);
$root = dirname(__DIR__);
$tzdata = timezone_version_get();

require_once $root . '/src/Core/Timezone/Support/AliasMap.php';

$caseName = static function (string $identifier): string {
    $name = str_replace(['+', '-'], [' Plus ', ' Minus '], $identifier);
    $name = str_replace(['/', '_'], ' ', $name);

    return str_replace(' ', '', ucwords(strtolower($name)));
};

/**
 * @param array<string, string> $cases case name => backed value
 */
$render = static function (string $class, string $concern, array $cases, string $summary) use ($tzdata): string {
    $body = '';

    foreach ($cases as $name => $value) {
        $body .= sprintf("    case %s = %s;\n", $name, var_export($value, true));
    }

    $count = count($cases);

    return <<<PHP
    <?php

    declare(strict_types=1);

    namespace Simtabi\\Laranail\\Chrono\\Core\\Enums;

    use Simtabi\\Laranail\\Chrono\\Core\\Enums\\Concerns\\{$concern};

    /**
     * GENERATED by tools/generate-enums.php — do not edit by hand.
     *
     * {$summary}
     *
     * {$count} cases, generated against tzdata {$tzdata}. Regenerate with `laranail::chrono.sync`.
     * A parity test asserts every case is a live identifier, every identifier has a case, and that
     * regenerating reproduces this file byte for byte.
     */
    enum {$class}: string
    {
        use {$concern};

    {$body}}

    PHP;
};

$emit = static function (string $path, string $contents) use ($check): bool {
    // Format first, so the bytes compared are the bytes that would be written.
    $contents = laranail_pint_format($contents);

    if ($check) {
        $existing = is_file($path) ? file_get_contents($path) : '';

        if ($existing !== $contents) {
            fwrite(STDERR, sprintf("%s is out of sync with the runner's tz database.\n", basename($path)));

            return false;
        }

        return true;
    }

    if (! is_dir(dirname($path))) {
        mkdir(dirname($path), 0o755, recursive: true);
    }

    file_put_contents($path, $contents);

    return true;
};

// ── canonical identifiers ───────────────────────────────────────────────────────────────────
$canonical = DateTimeZone::listIdentifiers(DateTimeZone::ALL);
$withBc = DateTimeZone::listIdentifiers(DateTimeZone::ALL_WITH_BC);

$build = static function (array $identifiers) use ($caseName): array {
    $cases = [];
    $seen = [];

    foreach ($identifiers as $identifier) {
        $name = $caseName($identifier);

        // Two identifiers normalising to one case name would be a fatal redeclaration in the
        // generated file. Refuse to write it rather than emit something that will not parse.
        if (isset($seen[$name])) {
            fwrite(STDERR, sprintf("case-name collision: %s and %s both become %s\n", $seen[$name], $identifier, $name));

            exit(1);
        }

        $seen[$name] = $identifier;
        $cases[$name] = $identifier;
    }

    return $cases;
};

$ok = true;

$ok = $emit(
    $root . '/src/Core/Enums/Timezone.php',
    $render('Timezone', 'ResolvesZone', $build($canonical), 'Every canonical IANA timezone identifier PHP knows.'),
) && $ok;

$legacy = array_values(array_diff($withBc, $canonical));

$ok = $emit(
    $root . '/src/Core/Enums/TimezoneLegacy.php',
    $render(
        'TimezoneLegacy',
        'ResolvesZone',
        $build($legacy),
        'Identifiers that exist only in the backward-compatible list: deprecated aliases such as '
        . '`Asia/Calcutta`, the fixed-offset `Etc/*` zones, and rule-bearing abbreviations like `CET`. '
        . 'Use `AliasMap` to find the canonical target, remembering that the `Etc/*` and abbreviation '
        . 'cases have none.',
    ),
) && $ok;

// ── abbreviations ───────────────────────────────────────────────────────────────────────────
$abbreviationCases = [];

foreach (array_keys(DateTimeZone::listAbbreviations()) as $abbreviation) {
    $abbreviationCases[strtoupper((string) $abbreviation)] = strtoupper((string) $abbreviation);
}

ksort($abbreviationCases);

$ok = $emit(
    $root . '/src/Core/Enums/TimezoneAbbreviation.php',
    $render(
        'TimezoneAbbreviation',
        'DescribesAbbreviation',
        $abbreviationCases,
        'Every timezone abbreviation PHP knows. Note most are ambiguous — 96 of these map to more '
        . 'than one zone, and `CST` alone matches 62 — so an abbreviation is a display label, never '
        . 'an identifier.',
    ),
) && $ok;

// ── the static constants class ──────────────────────────────────────────────────────────────
$constantName = static function (string $identifier): string {
    $name = str_replace(['+', '-'], ['_PLUS_', '_MINUS_'], $identifier);
    $name = preg_replace('/[^A-Za-z0-9]+/', '_', $name) ?? $name;

    return strtoupper(trim($name, '_'));
};

$constants = '';
$seenConstants = [];

foreach ($canonical as $identifier) {
    $name = $constantName($identifier);

    if (isset($seenConstants[$name])) {
        fwrite(STDERR, sprintf("constant-name collision: %s and %s both become %s\n", $seenConstants[$name], $identifier, $name));

        exit(1);
    }

    $seenConstants[$name] = $identifier;
    $constants .= sprintf("    public const string %s = %s;\n", $name, var_export($identifier, true));
}

$constantCount = count($seenConstants);

$tz = <<<TZ
<?php

declare(strict_types=1);

namespace Simtabi\\Laranail\\Chrono\\Core\\Enums;

use Simtabi\\Laranail\\Chrono\\Core\\Enums\\Concerns\\ListsTimezoneConstants;

/**
 * GENERATED by tools/generate-enums.php — do not edit by hand.
 *
 * Every canonical IANA identifier as a typed string constant, so a zone can be named without
 * spelling it out and without a typo surviving to runtime.
 *
 *     \\\$user->timezone = Tz::AFRICA_NAIROBI;      // not 'Africa/Nairobi'
 *     Timezones::of(Tz::AMERICA_NEW_YORK);
 *
 * This sits alongside the `Timezone` enum rather than replacing it, because the two are good at
 * different things. The enum carries behaviour — `->city()`, `->kind()`, `->toTimezone()` — and is
 * the right parameter type when a method must receive a real zone. These constants are plain
 * strings, so they drop straight into array keys, validation rules, config files, database writes
 * and query builders without `->value` on the end.
 *
 * {$constantCount} constants, generated against tzdata {$tzdata}. Regenerate with
 * `laranail::chrono.sync`; a parity test asserts every constant is a live identifier and that every
 * identifier has one.
 */
final class Tz
{
    use ListsTimezoneConstants;

{$constants}}

TZ;

$ok = $emit($root . '/src/Core/Enums/Tz.php', $tz) && $ok;
// ── the laranail/enumerator bridge ──────────────────────────────────────────────────────────
//
// This lives in the Laravel shell, not in Core. `laranail/enumerator` requires illuminate/*, and
// deptrac forbids Core from referencing any other Simtabi\Laranail package — that boundary is what
// keeps the domain testable without a container.
//
// It cannot be a decorator either: `Enumerator` is a marker interface whose behaviour comes from a
// trait the enum must `use` itself, so an adapter wrapping Core's enum would satisfy the interface
// without gaining any of the behaviour. A parallel enum is the honest shape, and since both are
// generated from one database by one algorithm they cannot drift.
$labelled = '';

foreach ($build($canonical) as $name => $identifier) {
    $city = str_replace('_', ' ', str_contains($identifier, '/')
        ? substr((string) strrchr($identifier, '/'), 1)
        : $identifier);

    $labelled .= sprintf(
        "    #[Label(%s)] case %s = %s;\n",
        var_export($city, true),
        $name,
        var_export($identifier, true),
    );
}

$bridge = <<<BRIDGE
<?php

declare(strict_types=1);

namespace Simtabi\\Laranail\\Chrono\\Enums;

use Simtabi\\Laranail\\Chrono\\Core\\Enums\\Timezone as CoreTimezone;
use Simtabi\\Laranail\\Chrono\\Core\\Timezone\\Value\\Timezone as TimezoneValue;
use Simtabi\\Laranail\\Enumerator\\Attributes\\Label;
use Simtabi\\Laranail\\Enumerator\\Concerns\\HasEnumeratorBehavior;
use Simtabi\\Laranail\\Enumerator\\Contracts\\Enumerator;

/**
 * GENERATED by tools/generate-enums.php — do not edit by hand.
 *
 * The `laranail/enumerator` view of the timezone catalogue: the same {$constantCount} identifiers as
 * `Core\\Enums\\Timezone`, with the house idiom applied so enumerator's casts, validation rules and
 * Blade components accept them.
 *
 * Two enums rather than one because `Core` is framework-free and `laranail/enumerator` requires
 * `illuminate/*`. Reach for this one when you want enumerator integration, and the Core enum when
 * you want the domain behaviour; `core()` and `toTimezone()` cross between them.
 *
 * Labels are the exemplar city, baked at generation time because `#[Label]` takes a literal. For a
 * localised name use `toTimezone()` and the formatter — ICU has translations for every locale, and
 * an English string frozen into a generated file does not.
 *
 * Generated against tzdata {$tzdata}. Regenerate with `laranail::chrono.sync`.
 */
enum TimezoneEnum: string implements Enumerator
{
    use HasEnumeratorBehavior;

{$labelled}
    /** The framework-free enum, for the domain behaviour this one deliberately does not carry. */
    public function core(): CoreTimezone
    {
        return CoreTimezone::from(\$this->value);
    }

    /** The value object: offsets, transitions, wall-clock resolution. */
    public function toTimezone(): TimezoneValue
    {
        return \$this->core()->toTimezone();
    }

    public static function fromCore(CoreTimezone \$timezone): self
    {
        return self::from(\$timezone->value);
    }
}

BRIDGE;

$ok = $emit($root . '/src/Enums/TimezoneEnum.php', $bridge) && $ok;
if ($check) {
    if (! $ok) {
        fwrite(STDERR, "Run `laranail::chrono.sync` to regenerate.\n");

        exit(1);
    }

    fwrite(STDOUT, sprintf("Generated enums are in sync (tzdata %s).\n", $tzdata));

    exit(0);
}

// The release every generated file in this repository corresponds to. Written by both generators,
// so it cannot drift from the data it describes.
file_put_contents(dirname(__DIR__) . '/resources/tzdata-version.txt', $tzdata . "\n");

fwrite(STDOUT, sprintf(
    "Wrote 3 enums + Tz + the enumerator bridge — %d canonical, %d legacy, %d abbreviations, %d constants, tzdata %s.\n",
    count($canonical),
    count($legacy),
    count($abbreviationCases),
    $constantCount,
    $tzdata,
));
